// DO NOT EDIT.
// Generated by internal/codegen.
// Source codex commit: be33f80bc65159c094ecd06bf155afa3061ce23d

package protocol

// GeneratedCodexCommit is the Codex source commit used to generate this protocol package.
const GeneratedCodexCommit = "be33f80bc65159c094ecd06bf155afa3061ce23d"

// GeneratedCodexVersion is the Codex package version used to generate this protocol package.
const GeneratedCodexVersion = "0.0.0"
